#!/usr/bin/env node
// Generate OpenAPI 3.1 components and service contract document from canonical schemas

import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  rmSync,
  readdirSync,
  statSync,
} from 'fs';
import { resolve, dirname, basename } from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '../../..');
const SCHEMAS_DIR = resolve(process.env.OPENAPI_SCHEMAS_DIR || resolve(ROOT, 'schemas'));
// Use environment variable for output directory, defaulting to committed path
const OPENAPI_OUTPUT_DIR = resolve(
  process.env.OPENAPI_OUTPUT_DIR || resolve(ROOT, 'packages/contracts/generated/openapi')
);

const COMMON_SCHEMAS = [
  'money.schema.json',
  'request-envelope.schema.json',
  'quote-request.schema.json',
  'quote-response.schema.json',
  'structured-error.schema.json',
  'service-metadata.schema.json',
  'async-job.schema.json',
  'pagination.schema.json',
  'authorized-artifact-reference.schema.json',
];

const SERVICE_SCHEMAS = [
  'company-evidence-input.schema.json',
  'company-evidence-output.schema.json',
  'web-context-input.schema.json',
  'web-context-output.schema.json',
  'document-evidence-input.schema.json',
  'document-evidence-output.schema.json',
  'agent-verification-input.schema.json',
  'agent-verification-output.schema.json',
];

// SUN-1000 checkpoint 1M: the active generation target moves to the v2
// service-major identities per checkpoint 1L's frozen
// PREPRODUCTION_V2_REPLACEMENT decision (section 25: "active OpenAPI =
// v2-only forward contract; frozen release 1.x = permanent v1 history").
// contracts/releases/1.0.0 and 1.0.1 are NOT regenerated by this change —
// both remain exactly as originally frozen, forever.
const SERVICE_MAJOR = process.env.OPENAPI_SERVICE_MAJOR || 'v2';
const CONTRACT_VERSION = process.env.OPENAPI_CONTRACT_VERSION || '2.0.0-preproduction';
const IS_DEFAULT_V2_GENERATION =
  SERVICE_MAJOR === 'v2' && CONTRACT_VERSION === '2.0.0-preproduction';
const SERVICE_IDS = {
  'company-evidence-output': `company_evidence_graph.${SERVICE_MAJOR}`,
  'web-context-output': `web_context_verified.${SERVICE_MAJOR}`,
  'document-evidence-output': `document_evidence_json.${SERVICE_MAJOR}`,
  'agent-verification-output': `verify_agent_output.${SERVICE_MAJOR}`,
};

/**
 * SUN-1000 checkpoint 1K-A root fix (defect A — invalid/unresolvable
 * component references, PATCH_REPAIR per checkpoint 1J).
 *
 * Prior to this fix, THREE independent naming derivations existed for
 * the same 8 service input/output schemas, and none of them was used
 * as the actual single source of truth for the others:
 *
 *   - `generateServiceComponents()`'s own registered component keys
 *     were derived from each schema *filename*
 *     (`company-evidence-input.schema.json` -> `CompanyEvidenceInput`).
 *   - The OpenAPI path `$ref`s in `generateServiceContractsOpenAPI()`
 *     were derived from each *service ID's own slug*
 *     (`company_evidence_graph.v1` -> `CompanyEvidenceGraphInput`).
 *   - The independently-generated Python models (`datamodel-codegen`,
 *     a separate tool, unmodified by this fix) derive class names from
 *     each schema's own `title` field
 *     (`"Company Evidence Graph Input"` -> `CompanyEvidenceGraphInput`).
 *
 * These three derivations do not agree in general — checkpoint 1J
 * verified this true for `company-evidence` (filename disagreed,
 * service-ID and title happened to agree) but checkpoint 1K-A's own
 * fuller check found `web-context` and `agent-verification` disagree
 * on all three. The only actually-authoritative, already-used-
 * elsewhere identity is each schema's own `title` field (Python's
 * generator already treats it as such). This function is now the
 * *single* place either the OpenAPI component keys or the OpenAPI
 * path `$ref`s derive a name from — eliminating the possibility of
 * the two ever disagreeing again by construction, rather than
 * special-casing the four services' current (broken) names.
 */
function titleToPascalCase(title: string): string {
  return title
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

const SERVICE_TITLES = {
  'company-evidence-output': 'Company Evidence Graph',
  'web-context-output': 'Verified Web Context',
  'document-evidence-output': 'Document Evidence JSON',
  'agent-verification-output': 'Agent Output Verification',
};

const SERVICE_PATHS = {
  [`company_evidence_graph.${SERVICE_MAJOR}`]: `/${SERVICE_MAJOR}/company/evidence-graph`,
  [`web_context_verified.${SERVICE_MAJOR}`]: `/${SERVICE_MAJOR}/web/context`,
  [`document_evidence_json.${SERVICE_MAJOR}`]: `/${SERVICE_MAJOR}/document/evidence-json`,
  [`verify_agent_output.${SERVICE_MAJOR}`]: `/${SERVICE_MAJOR}/verify/agent-output`,
};

const SERVICE_OPERATIONS: Record<string, string> = {
  [`company_evidence_graph.${SERVICE_MAJOR}`]: 'companyEvidenceGraph',
  [`web_context_verified.${SERVICE_MAJOR}`]: 'webContextVerified',
  [`document_evidence_json.${SERVICE_MAJOR}`]: 'documentEvidenceJson',
  [`verify_agent_output.${SERVICE_MAJOR}`]: 'verifyAgentOutput',
};

function run(cmd: string, args: string[], cwd: string = ROOT): string {
  try {
    const quotedCmd = cmd.includes(' ') ? `"${cmd}"` : cmd;
    const quotedArgs = args.map((arg) => (arg.includes(' ') ? `"${arg}"` : arg));
    const shellCmd = [quotedCmd, ...quotedArgs].join(' ');
    const result = execSync(shellCmd, { cwd, encoding: 'utf-8', stdio: 'pipe', shell: true });
    return result.toString().trim();
  } catch (e) {
    console.error(`Command failed: ${cmd} ${args.join(' ')}`);
    throw e;
  }
}

function readJson(filePath: string): any {
  return JSON.parse(readFileSync(filePath, 'utf-8'));
}

function writeJson(filePath: string, content: any): void {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, JSON.stringify(content, null, 2));
}

/** Reads each of the 8 service schema files' own `title` field once,
 * producing the single schema-base -> title-derived-PascalCase-name map
 * used consistently everywhere a service schema is referenced —
 * `generateServiceComponents()`'s own registered keys AND every
 * `https://siteborne.net/schemas/services/...` `$ref` conversion
 * (`convertRefs`, below), including references nested inside *other*
 * schemas (e.g. `RequestEnvelope`'s per-service conditional `input`
 * reference) — not just the top-level OpenAPI path `$ref`s. */
function loadServiceSchemaNameByBase(): Record<string, string> {
  const nameByBase: Record<string, string> = {};
  for (const schemaFile of SERVICE_SCHEMAS) {
    const schemaBase = schemaFile.replace('.schema.json', '');
    const schema = readJson(resolve(SCHEMAS_DIR, 'services', schemaFile));
    nameByBase[schemaBase] = titleToPascalCase(schema.title);
  }
  return nameByBase;
}

function sanitizeSchemaForOpenAPI(schema: any, serviceNameByBase: Record<string, string>): any {
  const sanitized = JSON.parse(JSON.stringify(schema));

  // Remove $schema and $id as they're not valid in OpenAPI
  delete sanitized.$schema;
  delete sanitized.$id;
  delete sanitized.examples;

  // Recursively process definitions
  if (sanitized.definitions) {
    for (const key of Object.keys(sanitized.definitions)) {
      sanitized.definitions[key] = sanitizeSchemaForOpenAPI(
        sanitized.definitions[key],
        serviceNameByBase
      );
    }
  }

  // Process properties
  if (sanitized.properties) {
    for (const key of Object.keys(sanitized.properties)) {
      sanitized.properties[key] = sanitizeSchemaForOpenAPI(
        sanitized.properties[key],
        serviceNameByBase
      );
    }
  }

  // Process items
  if (sanitized.items) {
    sanitized.items = sanitizeSchemaForOpenAPI(sanitized.items, serviceNameByBase);
  }

  // Process allOf, anyOf, oneOf
  for (const combinator of ['allOf', 'anyOf', 'oneOf']) {
    if (sanitized[combinator]) {
      sanitized[combinator] = sanitized[combinator].map((s: any) =>
        sanitizeSchemaForOpenAPI(s, serviceNameByBase)
      );
    }
  }

  // Convert $ref from full URLs to local OpenAPI component references
  function convertRefs(obj: any): any {
    if (typeof obj !== 'object' || obj === null) return obj;

    if (obj.$ref && typeof obj.$ref === 'string') {
      const ref = obj.$ref;
      if (ref.endsWith('/proof-carrying-context.schema.json')) {
        return { $ref: '#/components/schemas/PCCDocument' };
      }
      if (ref.startsWith('https://siteborne.net/schemas/common/')) {
        const name = ref
          .replace('https://siteborne.net/schemas/common/', '')
          .replace('.schema.json', '');
        return { $ref: `#/components/schemas/${toPascalCase(name)}` };
      }
      if (ref.startsWith('https://siteborne.net/schemas/services/')) {
        const base = ref
          .replace('https://siteborne.net/schemas/services/', '')
          .replace('.schema.json', '');
        const name = serviceNameByBase[base];
        if (!name) {
          throw new Error(
            `openapi_generation_unknown_service_ref: no title-derived name registered for "${base}" (referenced via ${ref})`
          );
        }
        return { $ref: `#/components/schemas/${name}` };
      }
      if (ref.startsWith('https://utility.siteborne.net/schemas/')) {
        const name = ref
          .replace('https://utility.siteborne.net/schemas/', '')
          .replace('.schema.json', '');
        return { $ref: `#/components/schemas/${toPascalCase(name)}` };
      }
    }

    for (const key of Object.keys(obj)) {
      obj[key] = convertRefs(obj[key]);
    }
    return obj;
  }

  return convertRefs(sanitized);
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_.]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function generateCommonComponents(serviceNameByBase: Record<string, string>): any {
  const components: any = { schemas: {} };

  // Load and sanitize each common schema
  for (const schemaFile of COMMON_SCHEMAS) {
    const schemaPath = resolve(SCHEMAS_DIR, 'common', schemaFile);
    const schema = readJson(schemaPath);
    const name = toPascalCase(schemaFile.replace('.schema.json', ''));
    components.schemas[name] = sanitizeSchemaForOpenAPI(schema, serviceNameByBase);
  }

  // Add PCC schema
  const pccPath = resolve(SCHEMAS_DIR, 'proof-carrying-context.schema.json');
  const pccSchema = readJson(pccPath);
  components.schemas.PCCDocument = sanitizeSchemaForOpenAPI(pccSchema, serviceNameByBase);

  return components;
}

/**
 * Builds components keyed by the single, already-computed
 * schema-base -> title-derived-name map (`loadServiceSchemaNameByBase`)
 * — the same map every `$ref` conversion (top-level path refs and
 * refs nested inside other schemas alike) also consumes, so they can
 * never disagree again by construction.
 */
function generateServiceComponents(serviceNameByBase: Record<string, string>): any {
  const components: any = { schemas: {} };

  for (const schemaFile of SERVICE_SCHEMAS) {
    const schemaBase = schemaFile.replace('.schema.json', '');
    const schemaPath = resolve(SCHEMAS_DIR, 'services', schemaFile);
    const schema = readJson(schemaPath);
    const name = serviceNameByBase[schemaBase];
    components.schemas[name] = sanitizeSchemaForOpenAPI(schema, serviceNameByBase);
  }

  return components;
}

function generateServiceContractsOpenAPI(): any {
  const openapi = {
    openapi: '3.1.0',
    info: {
      title: 'SITEBORNE Utility Network Service Contracts',
      version: CONTRACT_VERSION,
      description: IS_DEFAULT_V2_GENERATION
        ? 'Preproduction OpenAPI document for SITEBORNE Utility Network service contracts. SUN-1000 checkpoint 1M: the active/forward document now describes the v2 service-major identities (checkpoint 1L PREPRODUCTION_V2_REPLACEMENT decision; the frozen v1 contract remains permanently available at contracts/releases/1.0.0 and 1.0.1). No routes are production-enabled; the four per-service operations are locally fixture-verified (real HTTP behavior in fixture/sandbox mode only), while the quote endpoint remains not implemented.'
        : `Preproduction OpenAPI document for SITEBORNE Utility Network service contracts. This document describes the ${SERVICE_MAJOR} service-major identities. No routes are production-enabled; the four per-service operations are locally fixture-verified, while the quote endpoint remains not implemented.`,
    },
    servers: [
      {
        url: 'https://utility.siteborne.net',
        description: 'Preproduction server (not currently deployed)',
      },
    ],
    paths: {},
    components: {
      schemas: {},
    },
  };

  // Single source of truth for every service schema's name, computed
  // once and threaded through both component generators and every
  // $ref conversion (see `loadServiceSchemaNameByBase`).
  const nameByBase = loadServiceSchemaNameByBase();

  // Add common and service schemas to components
  const commonComponents = generateCommonComponents(nameByBase);
  const serviceComponents = generateServiceComponents(nameByBase);

  openapi.components.schemas = {
    ...commonComponents.schemas,
    ...serviceComponents.schemas,
  };

  // Add quote request/response schemas
  openapi.components.schemas.QuoteRequest = openapi.components.schemas.QuoteRequest;
  openapi.components.schemas.QuoteResponse = openapi.components.schemas.QuoteResponse;
  openapi.components.schemas.StructuredError = openapi.components.schemas.StructuredError;

  // SUN-1000 checkpoint 1M (defect B fix, checkpoint 1K-B/1L's frozen
  // MAJOR_CONTRACT_RELEASE decision): the per-service 400/402 responses
  // never actually matched StructuredError (checkpoint 1J section 10) —
  // the real runtime shapes, read directly from
  // apps/edge-api/src/control-plane/routes/x402-service.ts's jsonError()
  // (400) and its CDP-rail PAYMENT-REQUIRED challenge body (402), single
  // source of truth defined once here rather than duplicated per service.
  // StructuredError itself is untouched and remains correctly used for the
  // 500/quote-endpoint responses below, which were never part of defect B.
  openapi.components.schemas.ValidationError = {
    title: 'Validation Error',
    description:
      'Canonical 400 response shape actually returned by the paid-service route boundary (jsonError()) — not StructuredError, which was never emitted for this status code (SUN-1000 checkpoint 1K-B/1L defect-B correction).',
    type: 'object',
    additionalProperties: false,
    required: ['error', 'message'],
    properties: {
      error: { type: 'string', description: 'Stable machine-actionable error code.' },
      message: { type: 'string', description: 'Human-readable descriptive message.' },
      details: {
        description: 'Optional machine-actionable detail (e.g. schema validation errors).',
      },
    },
  };
  openapi.components.schemas.PaymentRequiredChallenge = {
    title: 'Payment Required Challenge',
    description:
      "Canonical 402 response shape actually returned by the paid-service route boundary's CDP-rail x402 PAYMENT-REQUIRED challenge — not StructuredError, which was never emitted for this status code (SUN-1000 checkpoint 1K-B/1L defect-B correction).",
    type: 'object',
    additionalProperties: false,
    required: ['error', 'x402_version', 'quote_id', 'requirement_id'],
    properties: {
      error: { type: 'string', const: 'payment_required' },
      x402_version: {
        type: 'integer',
        description: 'The x402 protocol version this challenge is issued under.',
      },
      quote_id: { type: 'string', description: 'The quote this challenge was minted against.' },
      requirement_id: {
        type: 'string',
        description: 'The payment requirement identifier to satisfy.',
      },
    },
  };

  // Inverse of SERVICE_IDS, stripping the '-output' suffix, so each
  // service ID resolves to its own schema-base (e.g. 'company-evidence')
  // — the single key `generateServiceComponents()` already used above.
  const serviceIdToSchemaBase: Record<string, string> = Object.fromEntries(
    Object.entries(SERVICE_IDS).map(([outputBase, id]) => [id, outputBase.replace(/-output$/, '')])
  );

  // Generate paths for each service
  for (const [serviceId, path] of Object.entries(SERVICE_PATHS)) {
    const operationId = SERVICE_OPERATIONS[serviceId];
    const schemaBase = serviceIdToSchemaBase[serviceId];
    const outputSchemaName = nameByBase[`${schemaBase}-output`];
    const inputSchemaName = nameByBase[`${schemaBase}-input`];

    openapi.paths[path] = {
      post: {
        operationId: `post${operationId}`,
        summary: `Execute ${SERVICE_TITLES[`${schemaBase}-output`]} service`,
        description: IS_DEFAULT_V2_GENERATION
          ? `Service contract for ${serviceId}. Locally fixture-verified (SUN-1000 checkpoint 1M) - not production-enabled.`
          : `Service contract for ${serviceId}. Locally fixture-verified - not production-enabled.`,
        'x-service-id': serviceId,
        'x-production-enabled': false,
        'x-implementation-status': 'local_fixture_verified',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: `#/components/schemas/${inputSchemaName}`,
              },
            },
          },
        },
        responses: {
          '200': {
            description: 'Successful response',
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${outputSchemaName}`,
                },
              },
            },
          },
          '400': {
            description: 'Invalid input',
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/ValidationError' },
              },
            },
          },
          '402': {
            description: 'Payment required',
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/PaymentRequiredChallenge' },
              },
            },
          },
          '500': {
            description: 'Internal server error',
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/StructuredError' },
              },
            },
          },
        },
      },
    };
  }

  // Add quote endpoint
  openapi.paths['/quotes/{service_id}'] = {
    post: {
      operationId: 'postQuote',
      summary: 'Request a quote for a service',
      description:
        'Returns a quote for the specified service. Not currently implemented - preproduction contract only.',
      'x-production-enabled': false,
      'x-implementation-status': 'not_implemented',
      parameters: [
        {
          name: 'service_id',
          in: 'path',
          required: true,
          schema: {
            type: 'string',
            enum: Object.keys(SERVICE_PATHS),
          },
        },
      ],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/QuoteRequest' },
          },
        },
      },
      responses: {
        '200': {
          description: 'Quote response',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/QuoteResponse' },
            },
          },
        },
        '400': {
          description: 'Invalid input',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/StructuredError' },
            },
          },
        },
        '404': {
          description: 'Service not found',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/StructuredError' },
            },
          },
        },
      },
    },
  };

  return openapi;
}

function main() {
  console.log('=== OpenAPI Generation ===\n');

  // Clean output directory
  if (existsSync(OPENAPI_OUTPUT_DIR)) {
    rmSync(OPENAPI_OUTPUT_DIR, { recursive: true, force: true });
  }
  mkdirSync(OPENAPI_OUTPUT_DIR, { recursive: true });

  const nameByBase = loadServiceSchemaNameByBase();

  // Generate common components
  console.log('Generating common components...');
  const commonComponents = generateCommonComponents(nameByBase);
  writeJson(resolve(OPENAPI_OUTPUT_DIR, 'common-components.json'), commonComponents);
  console.log(`  Generated: ${OPENAPI_OUTPUT_DIR}/common-components.json`);

  // Generate service components
  console.log('Generating service components...');
  const serviceComponents = generateServiceComponents(nameByBase);
  writeJson(resolve(OPENAPI_OUTPUT_DIR, 'service-components.json'), serviceComponents);
  console.log(`  Generated: ${OPENAPI_OUTPUT_DIR}/service-components.json`);

  // Generate combined service contracts OpenAPI document
  console.log('Generating combined service contracts OpenAPI...');
  const serviceContracts = generateServiceContractsOpenAPI();
  writeJson(resolve(OPENAPI_OUTPUT_DIR, 'service-contracts.openapi.json'), serviceContracts);
  console.log(`  Generated: ${OPENAPI_OUTPUT_DIR}/service-contracts.openapi.json`);

  console.log('\n✓ OpenAPI generation complete');
}

main();
